import { change } from '../core/state-utils.js';
import { clear, clearbtns, importmesh, createEvolutionBtn } from '../core/utils.js';

export function loadmuscular() {
    clear();
    clearbtns();
    change('loadmuscular(0)');
    importmesh("muscular_system.glb", new BABYLON.Vector3(0, 0, -100), new BABYLON.Vector3(0, -15, 0), 100, new BABYLON.Vector3(0.1, 0.1, 0.1), new BABYLON.Vector3(0, -15, 0));
    createEvolutionBtn("Gluteus Maximus", "Function: This muscle extends and externally rotates the hip.\nEvolutionary Perspective: The gluteus maximus is one of the most powerful muscles in the human body, essential for bipedal locomotion. Its size and strength are key adaptations for stabilizing the pelvis and enabling efficient running and climbing.");
    createEvolutionBtn("Quadriceps", "Function: This group of muscles extends the knee.\nEvolutionary Perspective: The quadriceps are vital for bipedalism, providing the necessary force for walking, running, and jumping. Their development is closely linked to the evolution of upright posture in humans.");
    createEvolutionBtn("Hamstrings", "Function: This group of muscles flexes the knee and extends the hip.\nEvolutionary Perspective: The hamstrings are crucial for efficient locomotion, working in opposition to the quadriceps. They have adapted to provide power and stability during bipedal movement.");
    createEvolutionBtn("Gastrocnemius", "Function: This muscle plantarflexes the foot and flexes the knee.\nEvolutionary Perspective: The gastrocnemius is essential for walking and running, providing the propulsive force needed to push off the ground. Its structure reflects adaptations for efficient bipedal locomotion.");
    createEvolutionBtn("Biceps Brachii", "Function: This muscle flexes the elbow and supinates the forearm.\nEvolutionary Perspective: In early primates, the biceps brachii was important for climbing and suspension. In humans, it has adapted for a wide range of manipulative tasks, from tool use to carrying objects.");
    createEvolutionBtn("Triceps Brachii", "Function: This muscle extends the elbow.\nEvolutionary Perspective: The triceps brachii is important for pushing movements. In primates, it plays a role in both locomotion and manipulation. Its development is linked to the diverse uses of the forelimbs in different species.");
    createEvolutionBtn("Rectus Abdominis", "Function: This muscle is responsible for flexing the lumbar spine.\nEvolutionary Perspective: The rectus abdominis plays a significant role in maintaining posture and stabilizing the core. Its evolution is tied to the demands of bipedalism and the need for a strong, stable trunk.");
    createEvolutionBtn("Obliques", "Function: The internal and external obliques are involved in trunk rotation and lateral flexion.\nEvolutionary Perspective: These muscles are essential for core stability and control. They have adapted to support the dynamic movements of the trunk required for bipedal locomotion and other complex activities.");
    createEvolutionBtn("Pectoralis Major", "Function: This muscle is responsible for movements of the shoulder joint, including flexion, adduction, and internal rotation.\nEvolutionary Perspective: In primates, the pectoralis major is important for climbing and upper body strength. Its size and shape reflect the diverse ways different species use their forelimbs.");
    createEvolutionBtn("Latissimus Dorsi", "Function: This muscle is involved in the extension, adduction, and internal rotation of the shoulder.\nEvolutionary Perspective: The latissimus dorsi is a large, powerful muscle of the back. In primates, it is crucial for climbing and other upper body movements. Its development is linked to the evolution of arboreal locomotion.");
    createEvolutionBtn("Deltoids", "Function: The deltoids are responsible for arm abduction, flexion, and extension.\nEvolutionary Perspective: In primates, the deltoids are important for a wide range of shoulder movements. Their evolution is linked to the need for both mobility and stability in the shoulder joint, allowing for complex tasks like tool use and climbing.");
    createEvolutionBtn("Trapezius", "Function: This muscle moves, rotates, and stabilizes the scapula and extends the neck.\nEvolutionary Perspective: The trapezius is important for posture and upper back stability. In primates, it supports the movements of the shoulder girdle, which is essential for climbing and other forelimb activities.");
    createEvolutionBtn("Soleus", "Function: This muscle plantar flexes the foot.\nEvolutionary Perspective: The soleus works with the gastrocnemius to provide the powerful plantarflexion needed for walking and running. It is a key adaptation for efficient bipedal locomotion.");
    createEvolutionBtn("Tibialis Anterior", "Function: This muscle dorsiflexes the foot and inverts the foot.\nEvolutionary Perspective: The tibialis anterior is crucial for controlling the position of the foot during walking and running. Its development is linked to the evolution of a stable, arched foot in humans.");
    createEvolutionBtn("Rectus Femoris", "Function: Part of the quadriceps group, it extends the knee and flexes the hip.\nEvolutionary Perspective: The rectus femoris is unique among the quadriceps because it crosses both the hip and knee joints. This allows it to play a role in both hip flexion and knee extension, making it important for complex movements like kicking and sprinting.");
    createEvolutionBtn("Supraspinatus", "Function: The supraspinatus is one of the four rotator cuff muscles that stabilize the shoulder and help with abduction of the arm.\nEvolutionary Perspective: The rotator cuff muscles are critical for the mobility and stability of the shoulder joint in primates. The supraspinatus, in particular, has adapted to support the wide range of arm movements needed for tasks like climbing and tool use.");
} 